# This workflow updates the plugin assets and readme on the WordPress.org repository when changes are pushed to the update-readme branch.
name: Plugin asset/readme update
on:
  workflow_dispatch:
jobs:
  update_assets_and_readme:
    if: github.repository == 'triopsi/extra-product-data-for-woocommerce'
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Cache Composer dependencies
        uses: actions/cache@v5
        with:
          path: ~/.composer/cache/files
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install Composer dependencies (no dev)
        run: composer install --no-dev --prefer-dist --no-interaction --no-progress
      - name: Optimize Composer autoload
        run: composer dump-autoload -o
      - name: Install npm dependencies
        run: npm ci
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SLUG: extra-product-data-for-woocommerce
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
